### ISSUE TITLE
Index.js not being saved in the correct directory

### ISSUE THREAD

**Issue by John-Jobin-McAuliffe** [ralphwetzel/node-red-systeminformation#1]
When I first installed this node it was working perfectly but this morning around 10 am EST node red temporarily crashed and when it rebooted the index.js file was not in the directory anymore causing the node to return build errors. I tried uninstalling all packages and reinstalling clean but the index.js file was missing from the directory again. Other users have been having the same issue. Hope this can be fixed soon, thank you for porting this library to node red as its very useful.

**Comment by ralphwetzel** [comment]
Thank you for reporting this issue.

> index.js file was not in the directory anymore

Have you been able to spot it again (e.g. moved to somewhere else) - or did it just disappear?

> index.js file was missing from the directory again.

I suppose you're referencing to the `index.js` file in folder `node-red-systeminformation`: I'm sorry; just ran a fresh installation from `npm` (via the Node-RED palette manager) and all files are - on my system - placed where they belong to. [npm](https://www.npmjs.com/package/@ralphwetzel/node-red-systeminformation?activeTab=code) shows the file being part of the package as well...

> Other users have been having the same issue.

I haven't noticed that. Could you share a link please to where this popped up...

**Comment by vk4tux** [comment]
https://discourse.nodered.org/t/ralphwetzel-node-red-systeminformation-does-not-load-in-ui-node-tools/84141

Just to verify, I do not think my issue is the same as OP. Just the ui node icon is missing so ui use is not available. See other issue. I posted here, as I know OP from another forum, however the issues seem differrent.

**Comment by John-Jobin-McAuliffe** [comment]
The file is just gone, best I can tell it hasn't moved anywhere else in the installation. I know some users are reporting that this is an issue with v16 and v18 of node red but I have not verified it yet. It's been a few posts on the node-red-hamradio groups.io forum and from what I've read it seems like it's been resolved. Have to wait till Tuesday till I'm back at my computer to test it though. The directory was @ralphwertzel/node-red-systeminformation. The file was originally there but disappeared when node red crashed and rebooted and refused to be readded when I did the reinstallation of the whole package. Thank you though for responding to my issue post, looking forward to testing the fix.

**Comment by John-Jobin-McAuliffe** [comment]
I've been able to retest it and I think my error is caused by something slightly different, namely the user account on my PC not having admin level access which is causing windows to not allow the index.js file to exist inside /node-red-systeminformation without an admin granting the permission for it to exist. Don't know why it did work temporarily, may have just taken a while for windows firewall to recognize the issue. Thank you again for responding to my issue report, going to close it out now that I know what the problem is.
